### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by pydupont** [phylocanvas/phylocanvas#1]
Hi,

The website for phylocanvas.org returns a 404 error. Where can I access the documentation of phylocanvas?

Cheers

**Comment by kabudahab** [comment]
Documentation is available at http://phylocanvas.org/

**Comment by pydupont** [comment]
Cheers

Pierre-Yves Dupont
Senior Scientist, Bioinformatician, ESR
Christchurch Science Centre, 27 Creyke Road, Christchurch 8041
DDI: +64 3 351 0099  / EXTN: 8099
E:  pierre.dupont@esr.cri.nz<mailto:pierre.dupont@esr.cri.nz>
W: www.esr.cri.nz<http://www.esr.cri.nz/>
[cid:image005.png@01D6970D.A460BAA0]<https://www.facebook.com/Institute-of-Environmental-Science-and-Research-190262607674473/> [cid:image006.png@01D6970D.A460BAA0] <https://twitter.com/ESRNewZealand>  [cid:image007.png@01D6970D.A460BAA0] <https://www.instagram.com/esrnewzealand/>
[cid:image004.png@01D6970D.A45BFFB0]
