### ISSUE TITLE
Image and Leaf ID Exports do not work on Firefox

### ISSUE THREAD

**Issue by richardgoater** [PhyloCanvas/PhyloCanvas#109]
Nothing happens.

**Comment by richardgoater** [comment]
After some investigation download links need to be explicitly clicked by the user in FF. Proposed solution is to add the link directly to the context menu. This requires some API changes and will be added to `release/2.0.0`.

**Comment by jyothishnt** [comment]
It seems like some issue with HTMLEvents in firefox. Also, `revokeObjectURL` was invoked before the download initiated and thus leaf id export was not working. Fixed. Please check #142
