### ISSUE TITLE
Node labels don't fit when nodeAlign is true

### ISSUE THREAD

**Issue by fedosejev** [PhyloCanvas/PhyloCanvas#114]
Fit node labels when `nodeAlign = true`. Currently this happens:

![image](https://cloud.githubusercontent.com/assets/5831566/8006802/eef13f1e-0b8e-11e5-98c1-a380001f8b51.png)

The workaround: `phylocanvas.setZoom(phylocanvas.zoom - 1);`

**Comment by jyothishnt** [comment]
@fedosejev @richardgoater Are you guys working with the latest version of PhyloCanvas?

**Comment by fedosejev** [comment]
@jyothishnt I am on `v1.7.1`
