### ISSUE TITLE
Internal `draw()` calls can really slow things down

### ISSUE THREAD

**Issue by richardgoater** [phylocanvas/phylocanvas#137]
Proposing to make client code call `draw` explicitly or use a `drawAfter` wrapping function:

``` javascript
tree.drawAfter(function () { 
  this.setNodeDisplay('A', { colour: 'red' });
  this.setNodeDisplay('B', { colour: 'blue' });
  this.setNodeDisplay('C', { colour: 'green' });
});
```

**Comment by richardgoater** [comment]
![pc](https://cloud.githubusercontent.com/assets/1429721/8783734/9abb05e2-2f15-11e5-9b7c-5fa435c415a8.png)

Case-in-point, triggered when a history snapshot is clicked. I think it's noticeably slow to change on large trees and this could be because of the duplicated `draw` call.

**Comment by jameshadfield** [comment]
(current as of v2.0.0-rc8)
Phylocanvas still redraws on every single mouseover event, despite no visual change. Specifically the draw function at https://github.com/PhyloCanvas/PhyloCanvas/blob/8849ce3c394f6fc693c9ad2d42a4ec57d67f50e2/src/Tree.js#L294 fires thousands of times as you move the mouse over the phylocanvas. 

Additionally (AFAIK) there is no specific listener for when phylocanvas has (visually) changed, so JScandy ends up running quite a bit of javascript every time phylocanvas redraws.
