### ISSUE TITLE
control zoom speed

### ISSUE THREAD

**Issue by jameshadfield** [phylocanvas/phylocanvas#170]
Is this possible via the API?

It seems that the phylocanvas implementations in the live demo, microreact and JScandy have vastly different zooming speeds (i'm not talking about rendering, but the amount of zoom on each event)

**Comment by tseemann** [comment]
+1 for this - a small sweep on the trackpad and it zooms to nothing/infinity instantly.

**Comment by simonrharris** [comment]
I think there's a zoomFactor variable in the Tree object that can be changed. The default is 0.2. Not sure if this would help with James' issue.
