### ISSUE TITLE
Error when Newick string does not end with a semicolon

### ISSUE THREAD

**Issue by kabudahab** [phylocanvas/phylocanvas#177]
The following error is thrown when the Newick string does not end with a semicolon:
```String not recognised as a file or a parseable format string```

**Comment by simonrharris** [comment]
I think by definition a Newick string should end with a semicolon, so perhaps this is a sensible check. It would be useful to report that it doesn't end with a semicolon, though.

**Comment by kabudahab** [comment]
Fixed in 9f0807e68cebc0c0625037b469d7f548d5354cf2
