### ISSUE TITLE
phylocanvas.org still hosting ancient version

### ISSUE THREAD

**Issue by tseemann** [phylocanvas/phylocanvas#178]
I've discovered the source of my confusion as to why I couldn't see all the new features I had heard about phylocanvas... i was looking at the phylocanvas.org website which still hosts 1.7 but I see now you are at 2.2 !

I don't want an NPM package but rather a standalone .js file to bundle with Nullarbor output. Can i just use the `dist/phylocanvas.min.js` for that?

**Comment by richardgoater** [comment]
Hi Torsten, sorry I missed this issue.

yes the that file should work if you haven't tried it already, doesn't have to be bundled in or anything.

**Comment by richardgoater** [comment]
Closing this as I've just added a holding page.
