### ISSUE TITLE
setNodeColourAndShape() in docs (v1.7) but not in 2.x

### ISSUE THREAD

**Issue by tseemann** [phylocanvas/phylocanvas#179]
Has the API changed a lot in 2.x vs 1.7 ?

Trying to use the docs at http://phylocanvas.org/ results in lots of errors with the 2.2 `dist/phylocanvas.js` code.

Or am I doing something wrong?

**Comment by richardgoater** [comment]
Sorry that it's not clear that those docs are out of date, I'll update the page today.

In the new API it's called `setNodeDisplay` and there are some examples here:
https://github.com/phylocanvas/phylocanvas/blob/master/dev/index.js#L92-L120

**Comment by tseemann** [comment]
I see it now says "v2.x docs coming soon."

**Comment by richardgoater** [comment]
it'll be like that until I can begin some documentation in a few weeks time, will leave this issue open till that gets done.

**Comment by tseemann** [comment]
I'm going to close this and make a new issue with a clearer title.
