### ISSUE TITLE
NPM module?

### ISSUE THREAD

**Issue by benjeffery** [phylocanvas/phylocanvas#182]
I'm looking to add phylocanvas to an existing project whose dependencies are managed via NPM. I can use a github repo URL, but this is far from ideal. Could the an NPM module be published?
Thanks!

**Comment by richardgoater** [comment]
Hello @benjeffery, thanks very much for your interest in the project!

I feel I only want to publish after completing some documentation of version 2, as the project will then be more discoverable for new users. I will be spending a portion of time on this every week for the next few weeks, so hopefully it shouldn't be too long.

In the meantime, we've been using github URLs successfully in the `package.json` of our own dependent projects for a while. I'm interested to know if this is causing you any problems in particular?

**Comment by benjeffery** [comment]
No worries, happy to continue using repo URLs for now. Not causing "problems" per se, but it is easier to manage versions/releases compared to commit hashes.

**Comment by richardgoater** [comment]
okay, that's good to know, thanks. We're finding tags to be useful enough as we're generating them with `npm version` anyway. Will keep this issue open till the module is published :+1:

**Comment by richardgoater** [comment]
Hi @benjeffery, please see Phylocanvas and plugins available on npm now. Let me know if you have any problems with the published packages.

**Comment by benjeffery** [comment]
Wonderful! Thanks!
I'll start using these when I come back from paternity leave, so don't expect any immediate feedback.

**Comment by richardgoater** [comment]
Ah, in that case, congratulations!
