### ISSUE TITLE
Ability to redraw subtree you have already selected

### ISSUE THREAD

**Issue by simonrharris** [phylocanvas/phylocanvas#183]
When you have chosen a subtree and are exploring it, it would be really useful to have an extra option in the right-click menu to redraw that subtree so that it can be refitted to the canvas rather than having to redraw the original tree and select the subtree again. This may be possible with the history, but when the history isn't being used it would be nice to be able to do this.

**Comment by richardgoater** [comment]
Hi Simon, I've added a "Fit in Panel" option and pushed v3.6.0 of the context menu plugin, hope this solves the problem?
