### ISSUE TITLE
JS Script usage issue

### ISSUE THREAD

**Issue by zachcp** [phylocanvas/phylocanvas#208]
Hi Team Phylocanvas,

This looks to be a really interesting and promising package.  It seems the docs/dev is oriented towards users of NPM (of which I am largely unschooled),  but I would like to be able to use this in a webpage as a script. I've noticed that while it is possible to initialize a phylocanvas from a script, it differs somewhat from the phylocanvas-quickstart documentation. For example, from an html webpage:

```[js]
// load the current github phylocanvas code
<script type="application/javascript" src="https://cdn.rawgit.com/phylocanvas/phylocanvas/master/dist/phylocanvas.js"> </script>

// doesn't work
tree = Phylocanvas.createTree("phylocanvas")

//works
tree = Phylocanvas.default.createTree("phylocanvas")
```

I am not really sure how the JS gets compiled but it would be very helpful to either change the build step to get a consistent method-calling structure, or, alternatively, to document that the initialization will be different when using a script.

thanks again for your great work,
zach cp

**Comment by richardgoater** [comment]
Hi @zachcp, thanks very much for your interest!

Thank you for highlighting the issue, I think we have intended the raw modules to be used with a bundler, leaving script usage to be covered by the quick start: http://phylocanvas.org/docs/quick-start/

Out of interest, is the quick start unsuitable for your use case?

Best,
Richard

**Comment by zachcp** [comment]
@richardgoater,  Thanks for the quick reply!

The quick start script is not a plain-vanilla tree. It has the history box and the length axis. While I think its great to have all plugins available, the most widely useable interface will be the simplest (in my opinion). Now that I know how to use the phylocanvas (I think!), I am fine, but I can imagine others wanting to plop a tree on a webpage and I would advocate that the best format is  a plain tree, possibly with the option to add plugins (zoom, select, etc.) and styling on top.

zach cp

**Comment by zachcp** [comment]
@richardgoater I've put together the skeleton of an R htmlwidgets package that will let you use phylocanvas from R. You can check it out here: https://zachcp.github.io/phylocanvas/

The basics work great and I solved the per-node styling issues. The next issue, related to the script vs. webpack layout is that I would like to optionally activate plugins for users. I'm hoping you may have a suggestion on this. Right now my options seem to be:

1. a custom build with all plugins activated 
2. load plugins as neccessary.

I would like to use 2 because then users can control what activated but I don't really see how to do that from the script-loading perspective. I tried to source the plugin JS but can't get it to work with the preloaded Phylocanvas. If you have any suggestions here then I'm off to the races. Alternatively is there a megabuild of phylocanvas will all plugins activated? I believe these could then be controlled via their options passed into the config object (it seems to work that way, anyhow).

Thanks again for your great work,
zach cp

**Comment by richardgoater** [comment]
Hi @zachcp, thanks very much for sharing your work, it looks great! It might make sense to move it into the Phylocanvas organisation one day if you'd like that? I could arrange it so you could maintain it from there.

Sorry that the plugins don't work perfectly without a bundler, it's something we need to work on. I think the quick start is the closest to a "mega build" that you're going to find right now. The plugins can be disabled with the following config:
```JavaScript
{
  history: false,
  contextMenu: false,
  scalebar: {
    active: false,
  },
}
```
Metadata only applies if a `data` property is added to a leaf.

Hope this helps, and thanks for the kind words. I'd love to be able to do a complete rewrite for version 3 to be honest :)

Best,
Richard

**Comment by zachcp** [comment]
Thanks for the heads-up Richard,

Let me play around with this a bit more before parking it anywhere, although I'm not opposed to the idea of adding this to the phylocanvas repo per-se.

I was able to use the phylocanvas-quickstart JS to decent effect. This has just about everything I could want - metadata, context menu, scale bar. I'll see how easy it will be to add/customize them.

Thanks again,
zach cp
