### ISSUE TITLE
Can't change text size with the quick start module

### ISSUE THREAD

**Issue by ctSkennerton** [phylocanvas/phylocanvas#209]
I downloaded the [quickstart application](http://phylocanvas.org/docs/quick-start/) but I've found that I'm unable to change the text size. I've taken the base script and changed to the following lines:

```
      var tree = Phylocanvas.createTree('phylocanvas');
      tree.setTextSize(30);
      tree.setNodeSize(30);
      tree.load('(A:0.1,B:0.2,(C:0.3,D:0.4)E:0.5)F;');
```

In my case the node size changes but not the text size.

**Comment by richardgoater** [comment]
Hi @ctSkennerton, thanks for your interest in Phylocanvas.

I think `tree.load` actually rescales the text, which is legacy behaviour that we have considered removing. Your best bet is to call `tree.setTextSize` after `tree.load`, and this should also call `tree.draw` for you automatically. Let me know if that doesn't work for you.

I will push an updated quickstart now, I notice that the current link is not working.

**Comment by richardgoater** [comment]
@ctSkennerton on further thought, I would recommend putting this call in an event listener like so:
```JavaScript
tree.on('loaded', function () {
  tree.setTextSize(30);
});
tree.load(newickString);
```

**Comment by ctSkennerton** [comment]
Yep, putting it in the event listener does the trick

**Comment by richardgoater** [comment]
@ctSkennerton glad to hear it, I will close this issue. Please feel free to open a new one if you have any more trouble.
