### ISSUE TITLE
Add the labels of the leaves as tooltip

### ISSUE THREAD

**Issue by anuprulez** [phylocanvas/phylocanvas#210]
I could not find a way to have labels of leaves to be displayed as tooltips. 

As it can be seen on the home page of Phylocanvas, the labels of the nodes are stacked over each other and cannot be seen easily. It would be a great feature to have tooltips not only for internal nodes but for leaf nodes as well.

![phylocanvas_home](https://cloud.githubusercontent.com/assets/3022518/24475700/18b6f80a-14d1-11e7-89d0-85b5cadfd6a3.png)

**Comment by richardgoater** [comment]
Hello, sorry for the late reply.

We're no longer working on this version. I'll transfer this issue to our v3 repo (currently private on Gitlab).

**Comment by kabudahab** [comment]
It is possible to display a tooltip on leaf nodes if you attach a mousemove event listener to the canvas and open the tooltip as in: https://github.com/phylocanvas/phylocanvas/blob/741cb733d68e0a5accfb225d6db9ad657c9f0fcb/src/Tree.js#L686
