### ISSUE TITLE
findBranch not a function

### ISSUE THREAD

**Issue by donnrriz** [phylocanvas/phylocanvas#211]
Hello 

I am calling the findBranch function , but getting findBranch is not a function

I also cannot see the findBranch function in the source ?  Can you tell me if I'm correct and if I should be using an alternative function ?

Im using the current npm version of phylocanvas

**Comment by richardgoater** [comment]
Hello, sorry for the late reply, I've stopped getting notifications from here.

There is no `findBranch` method unfortunately. Your best bet is to use the `branches` object on the tree instance.
