### ISSUE TITLE
How best to get a node by its id?

### ISSUE THREAD

**Issue by tseemann** [phylocanvas/phylocanvas#212]
If I want to change the shape of the node called `Reference` is this the simplest way?

```
var node = tree.findLeaves('Reference');  // returns 1 item but as an array
node[0].setDisplay( { shape: 'star', size: 2 } );
```

**Comment by richardgoater** [comment]
Hi Torsten, sorry for the late reply, I've stopped getting notifications from here for some reason.

I think
```
tree.branches['Reference'].setDisplay(...)
```
should be safe if your leaves and branches have unique ids. You can check that the branch is a leaf with the `leaf` flag.

**Comment by tseemann** [comment]
Thank you
There is plenty of issues for you to look at now you're back :-P

eg. https://github.com/phylocanvas/phylocanvas/issues/91
