### ISSUE TITLE
Black screen with webkit browser on mac

### ISSUE THREAD

**Issue by mubar003** [phylocanvas/phylocanvas#213]
Hello guys,
When I browse PhyloCanvas through the embedded webkit browser ex. javafx-netbeans on Mac OS X, the div or the tree turns black while moving the mouse. This problem “black screen” happens only with embedded webkit browser on mac system. Any consulting that could help to fix this bug ?

**Comment by kabudahab** [comment]
Phylocanvas requires canvas support, please refer to https://caniuse.com/#feat=canvas for a list of supported browsers.
