### ISSUE TITLE
Parse tree from PhyloXML

### ISSUE THREAD

**Issue by CIPowell** [phylocanvas/phylocanvas#3]
Add a parser to get tree from a PhyloXML string or file.

**Comment by richardgoater** [comment]
@PhyloCanvas/owners Any appetite for this? It's a very old issue!

**Comment by CorinY** [comment]
The citation list makes it seem like it is commonly produced/used in bioinformatics: https://scholar.google.com/scholar?cites=7075788753356347575. But maybe YAGNI?

**Comment by richardgoater** [comment]
@CorinY true, I suppose we can leave the issue open until someone +1s it.

**Comment by CorinY** [comment]
Open source JS library that may include a converter (it works with both formats anyway): http://www.jsphylosvg.com/ Plenty of official conversion libraries in other languages, so one may be coming for JS.
