### ISSUE TITLE
Zoom to mouse cursor position

### ISSUE THREAD

**Issue by richardgoater** [phylocanvas/phylocanvas#41]
Like Google Maps. Also, the sensitivity is too high on Chrome and too low on Firefox.

TODO:
- [x] Test HiDPI rendering / mouse accuracy
- [ ] Ensure "Fit in Panel" works for all tree types
- [x] Fix problems with History

**Comment by richardgoater** [comment]
Attempting to use http://phrogz.net/tmp/canvas_zoom_to_cursor.html as a template but thinking of scrapping this until it can be rewritten properly, there's too much re-working to do in one go in my opinion.

**Comment by richardgoater** [comment]
Hold that thought, I think I have some interactivity coming back...

**Comment by richardgoater** [comment]
Added TODO list.

**Comment by richardgoater** [comment]
pushing this out to a future minor release.

**Comment by jameshadfield** [comment]
This feature is needed for JScandy and appears to be related to issue #49
