### ISSUE TITLE
Tree does not render in Firefox on Ubuntu

### ISSUE THREAD

**Issue by richardgoater** [PhyloCanvas/PhyloCanvas#42]
Weird one...

**Comment by fedosejev** [comment]
No `canvas` support? Any error messages?

**Comment by richardgoater** [comment]
No errors and just a couple of lines drawn:
![phylocanvas](https://cloud.githubusercontent.com/assets/1429721/6859557/094c4084-d412-11e4-8b74-f4e950798b26.png)
The canvas is also unresponsive and can't be zoomed or manipulated.

**Comment by richardgoater** [comment]
Seems like it's a deep graphics problem with Firefox on Linux:
https://bugzilla.mozilla.org/show_bug.cgi?id=740200

I can get it working if I go to `about:config`, search "backends", change both from `cairo` to `skia`, but as the thread above explains this makes firefox's general graphics performance worse. Pretty serious bug on their end...

**Comment by richardgoater** [comment]
seems like it was actually a bug in the handling of `setLineDash` with incorrect parameters. This is fixed in `release/2.0.0` and could be backported if necessary.
