### ISSUE TITLE
Function to zoom to and/or centre selected nodes

### ISSUE THREAD

**Issue by richardgoater** [phylocanvas/phylocanvas#49]
https://github.com/ImperialCollegeLondon/microreact/issues/75 is depending on this issue.

**Comment by jyothishnt** [comment]
As of now it is zooming to the center of canvas which should be changed.
How about  zooming to cursor position?

**Comment by richardgoater** [comment]
Hi Jyo, sorry to be unclear, I mean that I would like to have a function that automatically brings selected nodes into view. This would solve the problem of not being able to find a selected node when looking at a large tree.

**Comment by jyothishnt** [comment]
Oh. Now I got it. Thanks Rich.

**Comment by jameshadfield** [comment]
This feature is needed for JScandy as well.
