### ISSUE TITLE
Code Modularity

### ISSUE THREAD

**Issue by richardgoater** [PhyloCanvas/PhyloCanvas#50]
FAO @jyothishnt @fedosejev 
Related to discussion in #36, I'm opening this issue to discuss ways to make the code easier to work with and easier to test.

I've been experimenting with Browserify in the branch `refactore-grande`, in which I managed to produce a minified file with a sourcemap for development. Couple this with modular files and I think we will have a much improved dev workflow.

Other options:
 - ES2015 modules with Babel, future-proof
 - Webpack as the build tool, provides module hot-loading and ability to bundle non-JS assets
 - Avoid extra cognitive overhead, just concatenate/minify separated JS files together and provide export mechanisms to Window, Browserify/Webpack et al.

**Comment by jyothishnt** [comment]
Yes it would give an improved/easy to use structure to the bundle.
Please check https://www.npmjs.com/package/browserify-css
Webpack - all in one?

**Comment by richardgoater** [comment]
@jyothishnt that's a really good find, solves the same issue. I think you have to do `npm install css-loader` to achieve the same in Webpack so it is equivalent. Webpack still has the ability to hot reload modules including CSS I think, but I have read a counter-argument that it is harder to set up. I will test the hot reloading on Friday and see if it is worth it.

**Comment by jyothishnt** [comment]
That will be awesome. Thanks Rich

**Comment by richardgoater** [comment]
Already included in `release/2.0.0`.
