### ISSUE TITLE
Unable to load NEWICK string with load function

### ISSUE THREAD

**Issue by fedosejev** [phylocanvas/phylocanvas#75]
`phylocanvas.load()` __silently__ fails to load a string with NEWICK data. However, it loads the same data via AJAX.

It would be great to have a function that simply sets tree data. It should assume that the data is passed as a `string` argument and it's a __valid NEWICK format__.

We can have 2 functions:
1. `dangerouslySetData(string)` - assumes that the data is valid and does no validation at all. Crashes the whole app if data is invalid.
2. `setData(string)` - assumes nothing about the data and validates it first. If data is invalid - throws a clear error message.

Please propose your solution first before implementing it.

**Comment by richardgoater** [comment]
Sorry Art, in what situation would you use `dangerouslySetData` over the normal one please?

**Comment by jyothishnt** [comment]
Hi Art, 
Here is an example on loading a string via load(). http://imperialcollegelondon.github.io/PhyloCanvas/docs/code_samples.html#cs_loadATreeFile
We need to check why it is failing for you. Could you please pass that newick file you used?

**Comment by fedosejev** [comment]
@richardgoater in a situation where I am doing my own NWK validation, even before PC is rendered. At that point, I can guarantee that it's valid.

**Comment by richardgoater** [comment]
@fedosejev thanks for the explanation, that sounds fair - it also questions whether PhyloCanvas should be responsible for newick validation at all, but that is a separate discussion!

**Comment by richardgoater** [comment]
@fedosejev this has just caused me a problem, loading via string tests a regex pattern before parsing the tree, but the ajax load does not. Unfortunately a clear error message from the regex is difficult to create, but in my case it was failing because of non-word characters in the node ids.

**Comment by tseemann** [comment]
I've just tried Phylocanvas and got caught by something like this as well.

The load() works with the example String and also with the example File. But when I used my own file named `phylo.tree` it failed silently, rendered nothing, console log was empty.

I finally figured out by scanning code that it *may* be using the file extension to decide how to handle it? But i'm not 100% sure.  By renaming it to `phylo.nwk` it worked. An explicit `load_newick()` or `load_file()` would be very helpful - along with some error messages. At minium, add a `.tree` extension to the parser - it's a common file extension.

**Comment by richardgoater** [comment]
Hi @tseemann, thanks for taking the time to write up your issue.

Am I right in thinking you're using the `master` branch? I'm happy to say this is code that I inherited and did not write, hence the untidiness. That said, I think you can specify newick format by writing:
```javascript
phylocanvas.load('./phylo.tree', null, 'newick');
```
In version 2 you will be able to write the following:
```javascript
phylocanvas.load('./phylo.tree', { format: 'newick' });
```
and I hope error-reporting will be better. 

Let me know if that doesn't work for you.

**Comment by tseemann** [comment]
@richardgoater No I was just using the latest `PhyloCanvas.js` "Download me" file. I also tried the remote `raw.github.com` URL as in the examples too. 

PS. I don't envy you inheriting a JS library!

**Comment by tseemann** [comment]
I've just used the `dist/phylocanvas.js` from HEAD and I can't load Newick files anymore :-(

**Comment by tseemann** [comment]
I just used `dist/phylocanvas.js`  from HEAD and now I can't load Newick files anymore with `load()` :-(

**Comment by richardgoater** [comment]
Hi @tseemann, can you post a snippet for me please? We've just merged version 2 which should use this format:
```JavaScript
phylocanvas.load('./phylo.tree', { format: 'newick' });
```
Also check out `dev/index.js` for a working example. You can run this after an `npm install` with `npm start`.
