### ISSUE TITLE
Parse and Show bootstrap value for each branch

### ISSUE THREAD

**Issue by jyothishnt** [phylocanvas/phylocanvas#91]

**Comment by richardgoater** [comment]
sorry @jyothishnt, what's the bootstrap value?

**Comment by richardgoater** [comment]
From Silvia:

((x2:0.45,x6:0.45)**74**:0.043,((x7:0.26,(x4:0.14,(x1:0.14,x3:0.14)**55**:0.0064)**68**:0.12)**100**:0.22,(x5:0.28,x8:0.28)**100**:0.2)**63**:0.011);

The bold values are Bootstrap values.

**Comment by jameshadfield** [comment]
This feature would be very useful in JScandy

**Comment by tseemann** [comment]
@richardgoater is there any chance you will add support for bootstrap value rendering? 
i has assumed phylocanvas supported it when i incorporated it into nullarbor, but now i'm stuck.

**Comment by richardgoater** [comment]
@tseemann We won't be adding anything more to this version. I'll make an issue on our (currently) private repo for v3 so that it doesn't get lost.

However I think you might be able to show these on v2 already, what happens if you set `showInternalNodeLabels` to true?

**Comment by richardgoater** [comment]
@tseemann when it's ready 🙂 However it is a part of the new Microreact, which needs to be done by the end of October. Hard part is getting a new docs site done, but we could release the source sooner.

**Comment by richardgoater** [comment]
@tseemann I'm glad! Don't think there's an example of it on the site so easy to miss, I think the v3 site will have a more comprehensive features section.

**Comment by tseemann** [comment]
@kabudahab will you make a v3 website?

**Comment by kabudahab** [comment]
Yes
