### ISSUE TITLE
Hide and show leaf

### ISSUE THREAD

**Issue by fedosejev** [PhyloCanvas/PhyloCanvas#94]
Would be great to have an API methods that allows to hide/show leaf:

```js
if (branch.leaf) {
 branch.hide();
 // then later... branch.show();
}
```

**Comment by jyothishnt** [comment]
We have 3 functions to do this
displayLabels()
hideLabels()
toggleLabels()
Is that what you are looking for?

**Comment by fedosejev** [comment]
@jyothishnt no, I would like to hide/show node itself, not only it's label.

**Comment by daanensen** [comment]
@jyothishnt -  the leaf icon/shape - square/circle etc (maybe we should decide on how we refer to that - icon??)

**Comment by jyothishnt** [comment]
OK. we can add this functionality. I think if you don't call the drawNode(), it should work.
